# The URL the site will be built for
base_url = "https://xie00059.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

[extra]
# Put all your custom variables here

# Author of the page
author = "Fuman Xie"

# Role of the author
role = "PhD Candidate"

# Organizations of the author
organizations = [ { name = "The University of Queensland" } ]

# Protrait photo
image = "/img/profile.jpg"

# Whether the navbar should be screen wide or page wide
wide_navbar = false

# Social icons that will appear under your profile box
social_icons = [
{icon="fa-envelope", icon_pack="fa", link="mailto:fuman.xie@uq.edu.au"},
{icon="ai-google-scholar", icon_pack="ai", link="https://scholar.google.com.my/citations?hl=en&pli=1&user=O_4wjM0AAAAJ"},
{icon="fa-github", icon_pack="fa-brands", link="https://github.com/xie00059" },
{icon="fa-linkedin", icon_pack="fa-brands", link="https://www.linkedin.com/in/fuman-xie-4b2083203/" },
]

# Your interests
interests = [
    { label = "Painting"},
    { label = "Travel"},
    { label = "History"},
]

# Your diplomas
education = [
{course = "Ph.D. in Computer Science", institution = "The University of Queensland, Australia", year = "2022-2025(Expected)", description = "Fully funded by UQ scholarship"},
{course = "M.Eng. in Software Field", institution = "The University of Queensland, Australia", year = "2020-2021"},
{course = "B.Eng. (Hons) in Software Engineering", institution = "The University of Queensland, Australia", year = "2016-2020"}
]

# Your work experience
career = [
{employer = "", year = "", title = ""},
]

# Your languages
languageskills = [
  {language = "English", proficiency = "Proficient"},
  {language = "Chinese", proficiency = "Proficient in Mandarin"},
]

# The ways people can contact you
# contact_links = [
#   {icon= " fa-envelope", icon_pack="fa", name = "Email me", link="mailto:email@example.com"},
#   {icon = "fa-twitter", icon_pack = "fab", name = "DM Me", link = "https://twitter.com/Twitter"},
#   {icon = "fa-skype", icon_pack = "fab", name = "Skype Me", link = "skype:echo123?call"},
#   {icon = "fa-keybase", icon_pack = "fab", name = "Chat on Keybase", link = "https://keybase.io/"},
#   {icon = "fa-comments", icon_pack = "fas", name = "Discuss on Forum", link = "https://zola.discourse.group/"},
#   {icon = "fa-discord", icon_pack = "fab", name = "John Doe #9999"},
# ]

# To download your CV files
cvlink = "cv-fuman-xie.pdf"
